name: Auto Merge

on:
  pull_request:
    branches: [master]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'

    steps:
      - name: Auto merge Renovate PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: 0
